# Generated by Django 3.0.2 on 2020-03-07 22:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20200223_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 22, 13, 18, 908493, tzinfo=utc)),
        ),
    ]
