# Generated by Django 3.0.2 on 2020-03-13 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20200307_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_balance',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='passive_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='../uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 14, 33, 59, 382511, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=30),
        ),
    ]
