# Generated by Django 3.0.2 on 2020-03-07 22:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_outgoing_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 22, 13, 18, 913594, tzinfo=utc)),
        ),
    ]
