# Generated by Django 3.0.2 on 2020-03-13 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200307_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 14, 33, 59, 385955, tzinfo=utc)),
        ),
    ]
